// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/recipes": {
    params: {};
  };
  "/recipes/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/checkout": {
    params: {};
  };
  "/livraison": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/stores": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/recipes" | "/recipes/:slug" | "/api/checkout" | "/livraison" | "/contact" | "/stores" | "/about" | "/shop" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/recipes._index.tsx": {
    id: "routes/recipes._index";
    page: "/recipes";
  };
  "routes/recipes.$slug.tsx": {
    id: "routes/recipes.$slug";
    page: "/recipes/:slug";
  };
  "routes/api.checkout.tsx": {
    id: "routes/api.checkout";
    page: "/api/checkout";
  };
  "routes/livraison.tsx": {
    id: "routes/livraison";
    page: "/livraison";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/stores.tsx": {
    id: "routes/stores";
    page: "/stores";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/jonysingla/Documents/dev/Websites/Cantine/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/recipes._index": typeof import("./app/routes/recipes._index.tsx");
  "routes/recipes.$slug": typeof import("./app/routes/recipes.$slug.tsx");
  "routes/api.checkout": typeof import("./app/routes/api.checkout.tsx");
  "routes/livraison": typeof import("./app/routes/livraison.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/stores": typeof import("./app/routes/stores.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/shop": typeof import("./app/routes/shop.tsx");
  "/Users/jonysingla/Documents/dev/Websites/Cantine/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};